<Project>
  <PropertyGroup>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

    <!-- Android -->
    <AndroidVersion>1.1.0</AndroidVersion>
    <AndroidReleaseDate>2026-10-05</AndroidReleaseDate>
    <AndroidApplicationVersion>3</AndroidApplicationVersion>
    <AndroidApplicationDisplayVersion>1.1.0</AndroidApplicationDisplayVersion>

    <!-- Windows -->
    <WindowsVersion>1.1.0</WindowsVersion>
    <WindowsReleaseDate>2026-10-06</WindowsReleaseDate>

    <!-- Linux -->
    <LinuxVersion>1.1.0</LinuxVersion>
    <LinuxReleaseDate>2026-10-05</LinuxReleaseDate>
  </PropertyGroup>

  <!-- Android project -->
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Android'))">
    <Version>$(AndroidVersion)</Version>
    <ReleaseDate>$(AndroidReleaseDate)</ReleaseDate>
    <ApplicationVersion>$(AndroidApplicationVersion)</ApplicationVersion>
    <ApplicationDisplayVersion>$(AndroidApplicationDisplayVersion)</ApplicationDisplayVersion>
  </PropertyGroup>

  <!-- Windows project -->
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Desktop'))">
    <ApplicationIcon>$(MSBuildThisFileDirectory)pallyFilePaste\Assets\PallyPasteFile_desktopIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="AndroidVersion" Value="$(AndroidVersion)" />
    <AssemblyMetadata Include="AndroidReleaseDate" Value="$(AndroidReleaseDate)" />

    <AssemblyMetadata Include="WindowsVersion" Value="$(WindowsVersion)" />
    <AssemblyMetadata Include="WindowsReleaseDate" Value="$(WindowsReleaseDate)" />

    <AssemblyMetadata Include="LinuxVersion" Value="$(LinuxVersion)" />
    <AssemblyMetadata Include="LinuxReleaseDate" Value="$(LinuxReleaseDate)" />
  </ItemGroup>
</Project>