<Project>

  <!-- Windows desktop -->
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'pallyFilePaste.Desktop' And $([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('win'))">
    <Version>$(WindowsVersion)</Version>
    <ReleaseDate>$(WindowsReleaseDate)</ReleaseDate>
  </PropertyGroup>

  <!-- Linux desktop -->
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'pallyFilePaste.Desktop' And $([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('linux'))">
    <Version>$(LinuxVersion)</Version>
    <ReleaseDate>$(LinuxReleaseDate)</ReleaseDate>
  </PropertyGroup>

</Project>